#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#mybatis别名
mybatis:
  type-aliases-package: com.xl.domain
#加载映射文件
  mapper-locations: classpath:mapper/*.xml
#设置日志，com.xl.mapper：只查看该包下程序的日志
logging:
  level:
    com:
      xl:
        mapper: debug
